### ISSUE TITLE
Copy and Paste is not working insinde CLI

### ISSUE THREAD

**Issue by Mafiat0m** [DeFiCh-WalletApp/WalletApp#12]
Desktop Defi Wallet for Windows Version 2.3.2

CTRL-C and STRL-V is not working in the CLI Command line. It is only working when hitting the functions in the Edit menu.

Die Tastenkombinationen CTRl-C und CTRL-V funktionieren nicht in der Konsole. Copy und Paste klappt nur, wenn man die Menüeinträge des Edit Tabs betätigt.

**Comment by p3root** [comment]
wrong repository!

You are looking for https://github.com/DeFiCh/app
