### ISSUE TITLE
Informationen bei Walleterstellung

### ISSUE THREAD

**Issue by jrm1990** [DeFiCh-WalletApp/WalletApp#15]
**Wallet version**
0.2.908

**Describe the bug**
Beschreibung / Meldung "was sind Wiederherstellungsschlüssel" ist bei Wallet-Anlegung, nach Neuinstallation, doppelt. 

Direkt zu Beginn und beim durchblättern nochmal. 

**To Reproduce**
Wallet anlegen

**Expected behavior**
Zweites Mal weg / überflüssig

**Screenshots**
![IMG_20210330_224133](https://user-images.githubusercontent.com/81651928/113053947-2c14e700-91a9-11eb-9613-011f006f48e4.jpg)
![IMG_20210330_224107](https://user-images.githubusercontent.com/81651928/113053952-2cad7d80-91a9-11eb-9a2f-83b0a5677b7d.jpg)

**Environment info**
 - Android
 
**Additional context**
Zusätzlicher Hinweis: t bei 'noch' zu viel
![IMG_20210330_224507](https://user-images.githubusercontent.com/81651928/113054724-0e944d00-91aa-11eb-8b6b-44bd92761861.jpg)

**Comment by p3root** [comment]
Fixed with https://github.com/DeFiCh-WalletApp/WalletApp/pull/16
